### PR TITLE
Fix types for `select` with object values

### PR DESCRIPTION
**Pull request by Silic0nS0ldier**
This PR implements the fix suggested in #7, and adds type test cases to validate.

It also restores most tests (`@testing-library/react` works quite differently to `enzyme`) which appear to have gone dark when knobs was split from the Storybook monorepo. While knobs may be deprecated, its important to my company that it remains stable while stories are migrated (fixing this type bug will also help since it'll simplify codemod development as part of migrating to addon-controls).

`yarn-error.log` was deleted, and marked for exclusion in `.gitignore`, which is what contributes to the 10k deletions the most.

### CODE REVIEW

**Comment by Silic0nS0ldier** [comment]
Pinging @shilman, since I have no way of knowing if this PR will be seen otherwise given addon-knobs is deprecated.

**Comment by shilman** [comment]
Thanks for the heads up @Silic0nS0ldier ! I will try to take a look this week. Please ping me if you get antsy. And thanks so much for the fixes!! 🙏

**Review by shilman — APPROVED** [review]
LGTM @Silic0nS0ldier -- merging & will release shortly

**Comment by shilman** [comment]
@Silic0nS0ldier released as `v6.3.1-next.0` -- can you please verify and i'll publish the patch version

**Comment by Silic0nS0ldier** [comment]
@shilman Fix in release verified to be working on my side.

**Comment by shilman** [comment]
@Silic0nS0ldier released as `v6.3.1` 🎉  thank you for the fix!!! 🙏

**Pull request merged**
